[package]
name    = "copperas"
version = "0.1.0"
authors = ["Vladimir Bogaevsky <vbogaevsky@gmail.com>"]

[dependencies]
gl           = "0.11.0"
glutin       = "0.18.0"
nalgebra-glm = "0.2.0"
serde        = "1.0.80"
serde_derive = "1.0.80"
toml         = "0.4.8"
